# Generated by Django 3.0 on 2020-01-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingChildren',
            fields=[
                ('child_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('sex', models.CharField(max_length=100)),
                ('complexion', models.CharField(max_length=100)),
            ],
        ),
    ]
