# Generated by Django 3.0 on 2020-01-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0003_stolenvehicle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StolenVehicle',
            new_name='StolenVehicles',
        ),
    ]
